/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BangKho
 */
public class Praktikum2 extends javax.swing.JFrame {
    String jns="";
    int jml;
    
    public Praktikum2() {
        initComponents();
        getJumlah();
        setJenis();
        panel.setVisible(false);
        pilihanbil.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        ket = new javax.swing.JLabel();
        bil1 = new javax.swing.JLabel();
        biljmlh = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        bil4 = new javax.swing.JLabel();
        pilihanbil = new javax.swing.JComboBox<>();
        b4 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        jenis = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROGRAM ARITMATIKA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 430, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Jenis Aritmatika ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 120, 30);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operasi", 0, 0, new java.awt.Font("Tahoma", 0, 12)))); // NOI18N
        panel.setLayout(null);

        ket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(ket);
        ket.setBounds(100, 30, 190, 30);

        bil1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bil1.setText("Bilangan 1");
        panel.add(bil1);
        bil1.setBounds(20, 110, 110, 30);

        biljmlh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        biljmlh.setText("Jumlah Bilangan");
        panel.add(biljmlh);
        biljmlh.setBounds(20, 70, 110, 30);

        bil2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bil2.setText("Bilangan 2");
        panel.add(bil2);
        bil2.setBounds(20, 150, 110, 30);

        bil3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bil3.setText("Bilangan 3");
        panel.add(bil3);
        bil3.setBounds(20, 190, 110, 30);

        bil4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bil4.setText("Bilangan 4");
        panel.add(bil4);
        bil4.setBounds(20, 230, 110, 30);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        panel.add(pilihanbil);
        pilihanbil.setBounds(210, 70, 150, 30);
        panel.add(b4);
        b4.setBounds(210, 230, 150, 30);

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        panel.add(b1);
        b1.setBounds(210, 110, 150, 30);
        panel.add(b2);
        b2.setBounds(210, 150, 150, 30);
        panel.add(b3);
        b3.setBounds(210, 190, 150, 30);

        button.setText("Hitung");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        panel.add(button);
        button.setBounds(140, 280, 110, 40);

        hasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        panel.add(hasil);
        hasil.setBounds(80, 330, 230, 40);

        getContentPane().add(panel);
        panel.setBounds(20, 90, 390, 390);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis", "Penjumlahan", "Pengurangan", "Pembagian", "Perkalian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(260, 50, 150, 30);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setForeground(new java.awt.Color(102, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 500);

        setBounds(0, 0, 447, 532);
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        double hsl = 0.0;
        double a1,a2,a3,a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
        a3 = Double.parseDouble(b3.getText().toString());
        a4 = Double.parseDouble(b4.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml==2){
                hsl=a1+a2;
                hasil.setText(a1+" + "+a2+" = "+hsl);
            } 
            if(jml==3){
                hsl=a1+a2+a3;
                hasil.setText(a1+" + "+a2+" + "+a3+" = "+hsl);
            }
            if(jml==4){
                hsl=a1+a2+a3+a4;
                hasil.setText(a1+" + "+a2+" + "+a3+" + "+a4+" = "+hsl);
            }
        } else if(jns.equals("Pengurangan")){
            if(jml==2){
                hsl=a1-a2;
                hasil.setText(a1+" - "+a2+" = "+hsl);
            } 
            if(jml==3){
                hsl=a1-a2-a3;
                hasil.setText(a1+" - "+a2+" - "+a3+" = "+hsl);
            }
            if(jml==4){
                hsl=a1-a2-a3-a4;
                hasil.setText(a1+" - "+a2+" - "+a3+" - "+a4+" = "+hsl);
            }
        } else if(jns.equals("Pembagian")){
            if(jml==2){
                hsl=a1/a2;
                hasil.setText(a1+" / "+a2+" = "+hsl);
            } 
            if(jml==3){
                hsl=a1/a2/a3;
                hasil.setText(a1+" / "+a2+" / "+a3+" = "+hsl);
            }
            if(jml==4){
                hsl=a1/a2/a3/a4;
                hasil.setText(a1+" / "+a2+" / "+a3+" / "+a4+" = "+hsl);
                
            } else if(jns.equals("Perkalian")){
            if(jml==2){
                hsl=a1*a2;
                hasil.setText(a1+" * "+a2+" = "+hsl);
            } 
            if(jml==3){
                hsl=a1*a2*a3;
                hasil.setText(a1+" * "+a2+" * "+a3+" = "+hsl);
            }
            if(jml==4){
                hsl=a1*a2*a3*a4;
                hasil.setText(a1+" * "+a2+" * "+a3+" * "+a4+" = "+hsl);
            }
    }//GEN-LAST:event_buttonActionPerformed
    }
    }
    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        getJumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed

   public void getJumlah(){
        if(pilihanbil.getSelectedItem().equals("2")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(false);
            bil4.setVisible(false);
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(false);
            b4.setVisible(false);
            jml=2;
        } else if(pilihanbil.getSelectedItem().equals("3")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(false);
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(false);
            jml=3;
        } else if(pilihanbil.getSelectedItem().equals("4")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            jml=4;
        }
    }
   
    public void setJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns="Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            pilihanbil.setVisible(true);
        } else if(jenis.getSelectedItem().equals("Pengurangan")){
            jns="Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            pilihanbil.setVisible(true);
        } else if(jenis.getSelectedItem().equals("Pembagian")){
            jns="Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            pilihanbil.setVisible(true);
        } else if(jenis.getSelectedItem().equals("Perkalian")){
            jns="Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            pilihanbil.setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktikum2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JLabel biljmlh;
    private javax.swing.JButton button;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilihanbil;
    // End of variables declaration//GEN-END:variables
}
